export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const FETCH_ANALYTICS = 'FETCH_ANALYTICS';
export const FETCH_VIDEOS = 'FETCH_VIDEOS';
export const FETCH_CHANNEL = 'FETCH_CHANNEL';
export const FETCH_PLAYLIST_ID = 'FETCH_PLAYLIST_ID';
